### ISSUE TITLE
bruh tf dis purguram

### ISSUE THREAD

**Issue by telugu-boy** [rizety/discantix#1]
tf ya gonna update ya program main, bin waitin' ta' b' usin' dis fa' a w0iel.
batch'a ain't gibin' m' wa' i b' payin' fa' ma bruh

**Comment by tripulse** [comment]
ight it do be ya muttha'phukkin endin @rizet

**Comment by rizet** [comment]
I am closing this issue due to language being used that is incredibly difficult to understand. If you still have this issue, please open another one with proper English.
